# Generated by Django 4.1 on 2022-08-30 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoiceform',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='invoiceform',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invoiceform',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='invoiceform',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.itemform'),
        ),
    ]
