# Generated by Django 4.1 on 2022-09-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoiceform_category_alter_invoiceform_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceform',
            name='category',
            field=models.TextField(choices=[('grocery', 'GROCERY'), ('electronics', 'ELECTRONICS')], null=True),
        ),
    ]
