# Generated by Django 4.1 on 2022-09-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoiceform_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemForm',
        ),
        migrations.AddField(
            model_name='invoiceform',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invoiceform',
            name='price',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invoiceform',
            name='quantity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='invoiceform',
            name='category',
            field=models.TextField(choices=[('grocery', 'GROCERY'), ('electronics', 'ELECTRONICS')], max_length=12),
        ),
    ]
