# Generated by Django 4.1 on 2022-09-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_delete_itemform_invoiceform_name_invoiceform_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceform',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='invoiceform',
            name='lname',
        ),
        migrations.AddField(
            model_name='invoiceform',
            name='itemname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invoiceform',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invoiceform',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
