# Generated by Django 4.1 on 2022-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_invoiceform_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceform',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
