# Generated by Django 4.0.7 on 2022-09-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoiceform_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceform',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoiceform',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoiceform',
            name='itemname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoiceform',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoiceform',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceform',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoiceform',
            name='quantity',
            field=models.TextField(),
        ),
    ]
